var hierarchy =
[
    [ "moteus::Aksim2", "d3/d09/classmoteus_1_1Aksim2.html", null ],
    [ "moteus::PID::ApplyOptions", "d5/d5f/structmoteus_1_1PID_1_1ApplyOptions.html", null ],
    [ "moteus::AS5047", "d7/d12/classmoteus_1_1AS5047.html", null ],
    [ "mjlib::micro::AsyncStream", null, [
      [ "moteus::Stm32G4AsyncUart", "d5/d34/classmoteus_1_1Stm32G4AsyncUart.html", null ]
    ] ],
    [ "moteus::AuxADC", "d2/d47/classmoteus_1_1AuxADC.html", null ],
    [ "moteus::aux::AuxConfig", "d5/d90/structmoteus_1_1aux_1_1AuxConfig.html", null ],
    [ "moteus::aux::AuxExtraOptions", "df/d51/structmoteus_1_1aux_1_1AuxExtraOptions.html", null ],
    [ "moteus::aux::AuxHardwareConfig", "dd/d73/structmoteus_1_1aux_1_1AuxHardwareConfig.html", null ],
    [ "moteus::AuxADC::AuxInfo", "d7/d0f/structmoteus_1_1AuxADC_1_1AuxInfo.html", null ],
    [ "moteus::aux::AuxPinConfig", "d8/dc9/structmoteus_1_1aux_1_1AuxPinConfig.html", null ],
    [ "moteus::AuxPort", "d9/d89/classmoteus_1_1AuxPort.html", null ],
    [ "moteus::aux::AuxStatus", "d7/d4c/structmoteus_1_1aux_1_1AuxStatus.html", null ],
    [ "moteus::BldcServo", "d8/d03/classmoteus_1_1BldcServo.html", null ],
    [ "moteus::BldcServoCommandData", "df/d31/structmoteus_1_1BldcServoCommandData.html", null ],
    [ "moteus::BldcServoConfig", "d7/d4f/structmoteus_1_1BldcServoConfig.html", null ],
    [ "moteus::BldcServoMotor", "d5/da2/structmoteus_1_1BldcServoMotor.html", null ],
    [ "moteus::BldcServoPosition", "d9/dcf/classmoteus_1_1BldcServoPosition.html", null ],
    [ "moteus::BldcServoPositionConfig", "d1/d3b/structmoteus_1_1BldcServoPositionConfig.html", null ],
    [ "moteus::BldcServoStatus", "d5/df2/structmoteus_1_1BldcServoStatus.html", null ],
    [ "moteus::BoardDebug", "dd/dcf/classmoteus_1_1BoardDebug.html", null ],
    [ "moteus::Stm32GpioInterruptIn::Callback", "db/d7e/structmoteus_1_1Stm32GpioInterruptIn_1_1Callback.html", null ],
    [ "moteus::ClarkTransform", "da/d5a/structmoteus_1_1ClarkTransform.html", null ],
    [ "moteus::ClockManager", "d4/dc4/classmoteus_1_1ClockManager.html", null ],
    [ "moteus::aux::Hall::Config", "d1/ddf/structmoteus_1_1aux_1_1Hall_1_1Config.html", null ],
    [ "moteus::aux::I2C::Config", "dc/d2a/structmoteus_1_1aux_1_1I2C_1_1Config.html", null ],
    [ "moteus::aux::Index::Config", "df/d13/structmoteus_1_1aux_1_1Index_1_1Config.html", null ],
    [ "moteus::aux::Quadrature::Config", "de/d7b/structmoteus_1_1aux_1_1Quadrature_1_1Config.html", null ],
    [ "moteus::aux::SineCosine::Config", "d8/d92/structmoteus_1_1aux_1_1SineCosine_1_1Config.html", null ],
    [ "moteus::aux::Spi::Config", "df/dcc/structmoteus_1_1aux_1_1Spi_1_1Config.html", null ],
    [ "moteus::aux::UartEncoder::Config", "de/da4/structmoteus_1_1aux_1_1UartEncoder_1_1Config.html", null ],
    [ "moteus::Drv8323::Config", "d2/d8d/structmoteus_1_1Drv8323_1_1Config.html", null ],
    [ "moteus::FDCan::Config", "dc/d8e/structmoteus_1_1FDCan_1_1Config.html", null ],
    [ "moteus::MotorPosition::Config", "df/dab/structmoteus_1_1MotorPosition_1_1Config.html", null ],
    [ "moteus::PID::Config", "d3/de9/structmoteus_1_1PID_1_1Config.html", null ],
    [ "moteus::SimplePI::Config", "d6/d55/structmoteus_1_1SimplePI_1_1Config.html", null ],
    [ "moteus::BldcServo::Control", "d4/dbb/structmoteus_1_1BldcServo_1_1Control.html", null ],
    [ "moteus::Cordic", "d7/d19/classmoteus_1_1Cordic.html", null ],
    [ "moteus::BoardDebug::Impl::Data", "d5/d01/structmoteus_1_1BoardDebug_1_1Impl_1_1Data.html", null ],
    [ "moteus::Uuid::Data", "da/d33/structmoteus_1_1Uuid_1_1Data.html", null ],
    [ "moteus::aux::I2C::DeviceConfig", "dd/d53/structmoteus_1_1aux_1_1I2C_1_1DeviceConfig.html", null ],
    [ "moteus::aux::I2C::DeviceStatus", "db/d10/structmoteus_1_1aux_1_1I2C_1_1DeviceStatus.html", null ],
    [ "moteus::Stm32G4AsyncUart::Impl::DmaFlags", "de/db7/structmoteus_1_1Stm32G4AsyncUart_1_1Impl_1_1DmaFlags.html", null ],
    [ "moteus::DqTransform", "da/d53/structmoteus_1_1DqTransform.html", null ],
    [ "moteus::FamilyAndVersion", "d5/d97/structmoteus_1_1FamilyAndVersion.html", null ],
    [ "moteus::FDCan", "dd/dd6/classmoteus_1_1FDCan.html", null ],
    [ "moteus::FDCan::Filter", "d9/d9c/structmoteus_1_1FDCan_1_1Filter.html", null ],
    [ "moteus::FDCan::FilterConfig", "df/ddb/structmoteus_1_1FDCan_1_1FilterConfig.html", null ],
    [ "moteus::FirmwareInfo", "db/da3/classmoteus_1_1FirmwareInfo.html", null ],
    [ "mjlib::micro::FlashInterface", null, [
      [ "moteus::Stm32G4Flash", "d1/dad/classmoteus_1_1Stm32G4Flash.html", null ]
    ] ],
    [ "moteus::detail::float_long", "dd/dfd/unionmoteus_1_1detail_1_1float__long.html", null ],
    [ "moteus::GitInfo", "d0/d52/structmoteus_1_1GitInfo.html", null ],
    [ "moteus::aux::Hall", "d9/d22/structmoteus_1_1aux_1_1Hall.html", null ],
    [ "moteus::BoardDebug::Impl::HistogramSource", "dd/deb/structmoteus_1_1BoardDebug_1_1Impl_1_1HistogramSource.html", null ],
    [ "moteus::aux::I2C", "da/d21/structmoteus_1_1aux_1_1I2C.html", null ],
    [ "moteus::IcPz", "da/dcc/classmoteus_1_1IcPz.html", null ],
    [ "moteus::BldcServo::Impl", "dc/dba/classmoteus_1_1BldcServo_1_1Impl.html", null ],
    [ "moteus::BoardDebug::Impl", "d7/dfc/classmoteus_1_1BoardDebug_1_1Impl.html", null ],
    [ "moteus::Drv8323::Impl", "df/d41/classmoteus_1_1Drv8323_1_1Impl.html", null ],
    [ "moteus::FirmwareInfo::Impl", "d5/d56/classmoteus_1_1FirmwareInfo_1_1Impl.html", null ],
    [ "moteus::Stm32G4AsyncUart::Impl", "d1/d08/classmoteus_1_1Stm32G4AsyncUart_1_1Impl.html", null ],
    [ "moteus::SystemInfo::Impl", "d7/da9/classmoteus_1_1SystemInfo_1_1Impl.html", null ],
    [ "moteus::aux::Index", "de/d41/structmoteus_1_1aux_1_1Index.html", null ],
    [ "moteus::InverseClarkTransform", "d3/d58/structmoteus_1_1InverseClarkTransform.html", null ],
    [ "moteus::InverseDqTransform", "d9/da4/structmoteus_1_1InverseDqTransform.html", null ],
    [ "moteus::InverseParkTransform", "d5/d17/structmoteus_1_1InverseParkTransform.html", null ],
    [ "mjlib::base::IsEnum< moteus::aux::AuxError >", "dd/d1f/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1aux_1_1AuxError_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::aux::I2C::DeviceConfig::Type >", "de/de2/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1aux_1_1I2C_1_1DeviceConfig_1_1Type_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::aux::Pin::Mode >", "d2/de0/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1aux_1_1Pin_1_1Mode_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::aux::Pin::Pull >", "dd/d59/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1aux_1_1Pin_1_1Pull_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::aux::Spi::Config::Mode >", "d7/d09/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1aux_1_1Spi_1_1Config_1_1Mode_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::aux::UartEncoder::Config::Mode >", "dc/dfc/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1aux_1_1UartEncoder_1_1Config_1_1Mode_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::BldcServoMode >", "d5/d70/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1BldcServoMode_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::Drv8323::OcpMode >", "d7/de0/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1Drv8323_1_1OcpMode_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::Drv8323::PwmMode >", "df/d78/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1Drv8323_1_1PwmMode_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::errc >", "db/d6a/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1errc_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::MotorPosition::SourceConfig::Reference >", "dc/da7/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1MotorPosition_1_1SourceConfig_1_1Reference_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::MotorPosition::SourceConfig::Type >", "d0/d74/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1MotorPosition_1_1SourceConfig_1_1Type_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::MotorPosition::Status::Error >", "db/df7/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1MotorPosition_1_1Status_1_1Error_01_4.html", null ],
    [ "mjlib::base::IsEnum< moteus::MotorPosition::Status::Homed >", "dd/de2/structmjlib_1_1base_1_1IsEnum_3_01moteus_1_1MotorPosition_1_1Status_1_1Homed_01_4.html", null ],
    [ "mjlib::multiplex::MicroDatagramServer", null, [
      [ "moteus::FDCanMicroServer", "df/d46/classmoteus_1_1FDCanMicroServer.html", null ]
    ] ],
    [ "moteus::MillisecondTimer", "d4/d16/classmoteus_1_1MillisecondTimer.html", null ],
    [ "moteus::MoteusController", "de/d69/classmoteus_1_1MoteusController.html", null ],
    [ "moteus::MoteusHwPins", "d0/d00/structmoteus_1_1MoteusHwPins.html", null ],
    [ "moteus::MotorDriver", "df/d1e/classmoteus_1_1MotorDriver.html", [
      [ "moteus::Drv8323", "da/dd3/classmoteus_1_1Drv8323.html", null ]
    ] ],
    [ "moteus::MotorPosition", "d5/d35/classmoteus_1_1MotorPosition.html", null ],
    [ "moteus::BldcServo::Options", "d5/d33/structmoteus_1_1BldcServo_1_1Options.html", null ],
    [ "moteus::Drv8323::Options", "d8/dd0/structmoteus_1_1Drv8323_1_1Options.html", null ],
    [ "moteus::FDCan::Options", "d9/dcb/structmoteus_1_1FDCan_1_1Options.html", null ],
    [ "moteus::Stm32BitbangSpi::Options", "d1/ddc/structmoteus_1_1Stm32BitbangSpi_1_1Options.html", null ],
    [ "moteus::Stm32G4AsyncUart::Options", "db/dac/structmoteus_1_1Stm32G4AsyncUart_1_1Options.html", null ],
    [ "moteus::Stm32G4DmaUart::Options", "d5/d60/structmoteus_1_1Stm32G4DmaUart_1_1Options.html", null ],
    [ "moteus::Stm32I2c::Options", "d5/d7a/structmoteus_1_1Stm32I2c_1_1Options.html", null ],
    [ "moteus::Stm32Serial::Options", "d8/d4b/structmoteus_1_1Stm32Serial_1_1Options.html", null ],
    [ "moteus::Stm32Spi::Options", "db/d45/structmoteus_1_1Stm32Spi_1_1Options.html", [
      [ "moteus::IcPz::Options", "df/d2b/structmoteus_1_1IcPz_1_1Options.html", null ]
    ] ],
    [ "moteus::MotorPosition::Config::Output", "df/df4/structmoteus_1_1MotorPosition_1_1Config_1_1Output.html", null ],
    [ "moteus::ParkTransform", "d6/de0/structmoteus_1_1ParkTransform.html", null ],
    [ "moteus::PID", "d9/d7e/classmoteus_1_1PID.html", null ],
    [ "moteus::aux::Pin", "d7/d42/structmoteus_1_1aux_1_1Pin.html", null ],
    [ "moteus::AuxADC::PinConfig", "d7/d58/structmoteus_1_1AuxADC_1_1PinConfig.html", null ],
    [ "moteus::aux::Quadrature", "dd/d51/structmoteus_1_1aux_1_1Quadrature.html", null ],
    [ "moteus::FDCan::Rate", "df/dbd/structmoteus_1_1FDCan_1_1Rate.html", null ],
    [ "moteus::FDCan::SendOptions", "d1/d9e/structmoteus_1_1FDCan_1_1SendOptions.html", null ],
    [ "moteus::FirmwareInfo::SerialNumber", "da/d10/structmoteus_1_1FirmwareInfo_1_1SerialNumber.html", null ],
    [ "multiplex::MicroServer::Server", null, [
      [ "moteus::MoteusController::Impl", "de/dff/classmoteus_1_1MoteusController_1_1Impl.html", null ]
    ] ],
    [ "moteus::SimplePI", "d3/dab/classmoteus_1_1SimplePI.html", null ],
    [ "moteus::SinCos", "d6/d13/structmoteus_1_1SinCos.html", null ],
    [ "moteus::aux::SineCosine", "d1/dfa/structmoteus_1_1aux_1_1SineCosine.html", null ],
    [ "moteus::MotorPosition::SourceConfig", "d5/d9e/structmoteus_1_1MotorPosition_1_1SourceConfig.html", null ],
    [ "moteus::MotorPosition::SourceStatus", "d9/d01/structmoteus_1_1MotorPosition_1_1SourceStatus.html", null ],
    [ "moteus::aux::Spi", "db/d19/structmoteus_1_1aux_1_1Spi.html", null ],
    [ "moteus::aux::SpiPinOption", "d6/d12/structmoteus_1_1aux_1_1SpiPinOption.html", null ],
    [ "moteus::PID::State", "d8/de0/structmoteus_1_1PID_1_1State.html", null ],
    [ "moteus::SimplePI::State", "d4/d05/structmoteus_1_1SimplePI_1_1State.html", null ],
    [ "moteus::aux::Hall::Status", "dd/d5b/structmoteus_1_1aux_1_1Hall_1_1Status.html", null ],
    [ "moteus::aux::I2C::Status", "d2/da7/structmoteus_1_1aux_1_1I2C_1_1Status.html", null ],
    [ "moteus::aux::Index::Status", "dc/d3a/structmoteus_1_1aux_1_1Index_1_1Status.html", null ],
    [ "moteus::aux::Quadrature::Status", "d3/db3/structmoteus_1_1aux_1_1Quadrature_1_1Status.html", null ],
    [ "moteus::aux::SineCosine::Status", "da/d11/structmoteus_1_1aux_1_1SineCosine_1_1Status.html", null ],
    [ "moteus::aux::Spi::Status", "da/d40/structmoteus_1_1aux_1_1Spi_1_1Status.html", null ],
    [ "moteus::aux::UartEncoder::Status", "da/d0a/structmoteus_1_1aux_1_1UartEncoder_1_1Status.html", null ],
    [ "moteus::Drv8323::Status", "d1/d7b/structmoteus_1_1Drv8323_1_1Status.html", null ],
    [ "moteus::IcPz::Status", "de/df9/structmoteus_1_1IcPz_1_1Status.html", null ],
    [ "moteus::MotorPosition::Status", "d4/dad/structmoteus_1_1MotorPosition_1_1Status.html", null ],
    [ "moteus::Stm32BitbangSpi", "d3/d6b/classmoteus_1_1Stm32BitbangSpi.html", null ],
    [ "moteus::Stm32DigitalMonitor", "d1/dfb/classmoteus_1_1Stm32DigitalMonitor.html", null ],
    [ "moteus::Stm32Dma", "d1/d9a/classmoteus_1_1Stm32Dma.html", null ],
    [ "moteus::Stm32G4DmaUart", "de/d4b/classmoteus_1_1Stm32G4DmaUart.html", null ],
    [ "moteus::Stm32GpioInterruptIn", "d3/d1f/classmoteus_1_1Stm32GpioInterruptIn.html", null ],
    [ "moteus::Stm32I2c", "db/d89/classmoteus_1_1Stm32I2c.html", null ],
    [ "moteus::aux::Stm32Index", "d3/deb/classmoteus_1_1aux_1_1Stm32Index.html", null ],
    [ "moteus::aux::Stm32Quadrature", "db/d42/classmoteus_1_1aux_1_1Stm32Quadrature.html", null ],
    [ "moteus::Stm32Serial", "d8/dc2/classmoteus_1_1Stm32Serial.html", null ],
    [ "moteus::Stm32Spi", "d8/d80/classmoteus_1_1Stm32Spi.html", null ],
    [ "moteus::StreamWriter< Size, NumCallbacks >", "d0/dc0/classmoteus_1_1StreamWriter.html", null ],
    [ "moteus::SystemInfo", "df/df9/classmoteus_1_1SystemInfo.html", null ],
    [ "moteus::TimingInput", "d1/d76/structmoteus_1_1TimingInput.html", null ],
    [ "moteus::TimingResult", "d2/d9f/structmoteus_1_1TimingResult.html", null ],
    [ "moteus::TorqueModel", "dc/d21/classmoteus_1_1TorqueModel.html", null ],
    [ "std::true_type", null, [
      [ "mjlib::micro::is_error_code_enum< moteus::errc >", "da/d33/structmjlib_1_1micro_1_1is__error__code__enum_3_01moteus_1_1errc_01_4.html", null ]
    ] ],
    [ "moteus::aux::UartEncoder", "d4/d9f/structmoteus_1_1aux_1_1UartEncoder.html", null ],
    [ "moteus::aux::UartPinOption", "d1/d8a/structmoteus_1_1aux_1_1UartPinOption.html", null ],
    [ "moteus::Uuid", "d2/d00/classmoteus_1_1Uuid.html", null ],
    [ "moteus::Vec3", "df/dd1/structmoteus_1_1Vec3.html", null ]
];